spring:
  application:
    name: cave-a-vin
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=CAVE_A_VIN;integratedSecurity=false;encrypt=false;trustServerCertificate=false
    username: sa
    password: Pa$$w0rd
  messages:
    encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  web:
    locale: en_GB
  mongodb:
    username: sa
    password: Passw0rd
    host: 10.171.200.18
    port: 27017
    database: Gestion_Avis
    authentication-database: admin

app:
  jwt:
    secret: 546f6b7056734479323031265f592148623f6c3a3a3f7928707d475323

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG